appName: facilgo-api
namespace: facilgo-api-dev
environment: development
deployment:
  name: facilgo-api-depl

service:
  name: facilgo-api-srv
  type: LoadBalancer
  port: 80
  targetPort: 8000
config:
  name: facilgo-srv-config

image:
  name: registry.digitalocean.com/facilgo-test/api-prediction
  tag: "latest"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  path: /api

secret:
  metadata:
    name: facilgo-api-secrets
volume:
  config_name: facilgo-config-volume
  secret_name: facilgo-secret-volume