apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: facilgo-api
  namespace: argocd
  labels:
    name: facilgo-api
spec:
  project: default
  source:
    repoURL: https://github.com/Facilgo/facilgo-api.git
    targetRevision: deployment
    path: /infra/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: facilgo

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
