apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: facilgo-api
  namespace: argocd
  labels:
    name: facilgo-api
spec:
  project: default
  source:
    repoURL: https://github.com/nkoppala-facilgo/deployment.git
    targetRevision: HEAD
    path: facilgo
    helm:
      releaseName: my-app-release
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: facilgo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
