apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: facilgo-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nkoppala-facilgo/deployment.git
    targetRevision: main
    path: facilgo
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: facilgo-api
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true