apiVersion: v1
kind: Secret
metadata:
  name: facilgo-srv-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  NODE_ENV: ZGV2ZWxvcG1lbnQ=
  DATABASE_PORT: MzMwNg==
  DATABASE_POOL_MIN: MA==
  DATABASE_POOL_MAX: MTAw
  AES_KEY: ZGV2ZWxvcG1lbnQ=
  AES_IV: bW9uZ29wYXNzd29yZA==
  ASSET_HOST_URL: aHR0cHM6Ly9kMXZ1eHhuN2phbnd3YS5jbG91ZGZyb250Lm5ldC91cGxvYWRzL3BpY3R1cmUvcGljdHVyZV91cmw=
