appName: facilgo-reno-reno
namespace: facilgo-dev
deployment:
  name: facilgo-reno-depl

service:
  name: facilgo-reno-srv
  type: NodePort
  port: 3005
config:
  name: facilgo-reno-srv-config

image:
  name: registry.digitalocean.com/facilgo/facilgo-reno
  tag: "latest"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  path: /ui

secret:
  metadata:
    name: facilgo-reno-secrets

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

  