apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-depl
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          imagePullSecrets:
            - name: docker-login-do
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.config.name }}
                  key: NODE_ENV
          resources:
            requests:
              cpu: 125m
              memory: 100Mi
            limits:
              cpu: 250m
              memory: 126Mi
          volumeMounts:
            - name: facilgo-reno-secret-volume
              mountPath: /secrets/
            - name: facilgo-reno-config-volume
              mountPath: /configs/
      volumes:
        - name: facilgo-reno-config-volume
          configMap:
            name: facilgo-reno-srv-config #name of our configmap object
        - name: facilgo-reno-secret-volume
          secret:
            secretName: facilgo-reno-srv-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: {{ .Values.appName }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
