apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-depl
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag}}"
          # imagePullSecrets:
          #   - name: dckr_pat_gUoRMw6To2z0I6ZriDiUHWQbLhY
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.config.name }}
                  key: NODE_ENV
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: api-srv-secret
                  key: DATABASE_PORT
            - name: DATABASE_POOL_MIN
              valueFrom:
                secretKeyRef:
                  name: api-srv-secret
                  key: DATABASE_POOL_MIN
            - name: DATABASE_POOL_MAX
              valueFrom:
                secretKeyRef:
                  name: api-srv-secret
                  key: DATABASE_POOL_MAX
            - name: AES_KEY
              valueFrom:
                secretKeyRef:
                  name: api-srv-secret
                  key: AES_KEY
            - name: AES_IV
              valueFrom:
                secretKeyRef:
                  name: api-srv-secret
                  key: AES_IV
