apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: {{ .Values.appName }}
      # protocol: TCP
      port: 8000
      targetPort: 8000
